version: '3.1'
services:
  bookmedik:
    container_name: contenedor-bookmedik-v2
    image: alfonsora6/bookmedik:v2
    restart: always
    environment:
      USER_BOOKMEDIK: admin
      PASS_BOOKMEDIK: admin
      DATABASE_HOST: contenedor-mariadb-v2
      NOMBRE_DB: bookmedik
    ports:
      - 8081:80
    depends_on:
      - db
  db:
    container_name: contenedor-mariadb-v2
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bookmedik
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data: