version: '3.1'
services:
  bookmedik:
    container_name: contenedor_bookmedik
    image: alfonsora6/bookmedik:v1
    restart: always
    environment:
      USER_BOOKMEDIK: admin
      PASS_BOOKMEDIK: admin
      DATABASE_HOST: contenedor_mariadb
      NOMBRE_DB: bookmedik
    ports:
      - 8086:80
    depends_on:
      - db
  db:
    container_name: contenedor_mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bookmedik
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data:
